// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechGearAPI.Data;

#nullable disable

namespace TechGearAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260206064643_Seed5Data")]
    partial class Seed5Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TearGearAPI.Model.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TechGearAPI.Models.ApplicationUserAPI", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d4e0542f-2685-4558-a41f-ae590896fe1e",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "demo1@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Demo User 1",
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DEMO1@GMAIL.COM",
                            NormalizedUserName = "DEMO1",
                            PasswordHash = "AQAAAAIAAYagAAAAEDSWb701hsafCOB1ln+/C3yT3LwoqUm7ab0fq8AxQ6P89B6fA04y2rZboHHRUbDzMA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ba04c214-0082-4556-9f09-81b37f61014f",
                            TwoFactorEnabled = false,
                            UserName = "demo1"
                        },
                        new
                        {
                            Id = "user2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ab317806-653d-4abd-91e4-94be264e3241",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "demo2@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Demo User 2",
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DEMO2@GMAIL.COM",
                            NormalizedUserName = "DEMO2",
                            PasswordHash = "AQAAAAIAAYagAAAAEM/tx5rmcYc4v+BcklvhS9Voc82cc1t1gZ5X6KTVX/7X6BOaIKOceOvToNG9gyFVag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2fae543b-6beb-4e91-b040-fc6423ca2bba",
                            TwoFactorEnabled = false,
                            UserName = "demo2"
                        },
                        new
                        {
                            Id = "user3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "26394bfc-d58a-40f1-9f2c-cc99e05650e2",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "demo3@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Demo User 3",
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DEMO3@GMAIL.COM",
                            NormalizedUserName = "DEMO3",
                            PasswordHash = "AQAAAAIAAYagAAAAEB/rmpwjhk/1/+hl+OiD3tTKAQhEV/kt99aH2DN4G94EmFdGpfroRn1uGElG83068g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d48c24cd-5664-4ffc-a2c3-2a60e0994ce3",
                            TwoFactorEnabled = false,
                            UserName = "demo3"
                        },
                        new
                        {
                            Id = "user4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7340b77e-d29b-497c-8575-84883b3d3a88",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "demo4@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Demo User 4",
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DEMO4@GMAIL.COM",
                            NormalizedUserName = "DEMO4",
                            PasswordHash = "AQAAAAIAAYagAAAAEDhyf9PQozw6SYc2TMV5rLol++UJBXVXBgTn3ZTrHanvjg6WLsfKeBemEXflOlHYuQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a4f15736-bf8b-40e5-b3b0-37e3c6cdd4b2",
                            TwoFactorEnabled = false,
                            UserName = "demo4"
                        },
                        new
                        {
                            Id = "user5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d37d306a-c95a-42ec-a43a-105f29a3f688",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "demo5@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Demo User 5",
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DEMO5@GMAIL.COM",
                            NormalizedUserName = "DEMO5",
                            PasswordHash = "AQAAAAIAAYagAAAAEBpxtjDoZBRmOpzTYewp7PhewrEMWJVSG6X7OTQhPgFZ5Z0RhkAhnHFK8C2IjvtKXQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "59bb3e0b-c9f1-430a-b612-af65f40694e2",
                            TwoFactorEnabled = false,
                            UserName = "demo5"
                        });
                });

            modelBuilder.Entity("TechGearAPI.Models.BrandAPI", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("brandAPIs");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "ASUS",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Logitech",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Razer",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Dell",
                            IsActive = true
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "Sony",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("TechGearAPI.Models.CartItemAPI", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("UserId", "ProductVariantId")
                        .IsUnique();

                    b.ToTable("cartItemAPIs");

                    b.HasData(
                        new
                        {
                            CartItemId = 1,
                            ProductVariantId = 1,
                            Quantity = 1,
                            UserId = "user1"
                        },
                        new
                        {
                            CartItemId = 2,
                            ProductVariantId = 2,
                            Quantity = 2,
                            UserId = "user2"
                        },
                        new
                        {
                            CartItemId = 3,
                            ProductVariantId = 3,
                            Quantity = 1,
                            UserId = "user3"
                        },
                        new
                        {
                            CartItemId = 4,
                            ProductVariantId = 4,
                            Quantity = 1,
                            UserId = "user4"
                        },
                        new
                        {
                            CartItemId = 5,
                            ProductVariantId = 5,
                            Quantity = 3,
                            UserId = "user5"
                        });
                });

            modelBuilder.Entity("TechGearAPI.Models.CategoryAPI", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("categoryAPIs");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Laptop",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Mouse",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Keyboard",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Monitor",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Headphone",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("TechGearAPI.Models.ComboAPI", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboId"));

                    b.Property<int>("ComboItemId")
                        .HasColumnType("int");

                    b.Property<string>("ComboName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("OriginalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ComboId");

                    b.ToTable("comboAPIs");

                    b.HasData(
                        new
                        {
                            ComboId = 1,
                            ComboItemId = 0,
                            ComboName = "Gaming Set 1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountType = 1,
                            DiscountValue = 5m,
                            FinalPrice = 21000000m,
                            IsActive = true,
                            OriginalPrice = 22000000m
                        },
                        new
                        {
                            ComboId = 2,
                            ComboItemId = 0,
                            ComboName = "Gaming Set 2",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountType = 1,
                            DiscountValue = 10m,
                            FinalPrice = 2700000m,
                            IsActive = true,
                            OriginalPrice = 3000000m
                        },
                        new
                        {
                            ComboId = 3,
                            ComboItemId = 0,
                            ComboName = "Office Set",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountType = 2,
                            DiscountValue = 500000m,
                            FinalPrice = 5500000m,
                            IsActive = true,
                            OriginalPrice = 6000000m
                        },
                        new
                        {
                            ComboId = 4,
                            ComboItemId = 0,
                            ComboName = "Streamer Set",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountType = 2,
                            DiscountValue = 500000m,
                            FinalPrice = 6500000m,
                            IsActive = true,
                            OriginalPrice = 7000000m
                        },
                        new
                        {
                            ComboId = 5,
                            ComboItemId = 0,
                            ComboName = "Audio Set",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountType = 1,
                            DiscountValue = 7m,
                            FinalPrice = 2800000m,
                            IsActive = true,
                            OriginalPrice = 3000000m
                        });
                });

            modelBuilder.Entity("TechGearAPI.Models.ComboItemAPI", b =>
                {
                    b.Property<int>("ComboItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboItemId"));

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ComboItemId");

                    b.HasIndex("ComboId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("comboItems");

                    b.HasData(
                        new
                        {
                            ComboItemId = 1,
                            ComboId = 1,
                            ProductVariantId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            ComboItemId = 2,
                            ComboId = 2,
                            ProductVariantId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            ComboItemId = 3,
                            ComboId = 3,
                            ProductVariantId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            ComboItemId = 4,
                            ComboId = 4,
                            ProductVariantId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            ComboItemId = 5,
                            ComboId = 5,
                            ProductVariantId = 5,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("TechGearAPI.Models.OrderAPI", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserAddressId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("orderAPIs");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippingFee = 50000m,
                            Status = 1,
                            SubTotal = 20000000m,
                            TotalAmount = 20050000m,
                            UserAddressId = 1,
                            UserId = "user1"
                        },
                        new
                        {
                            OrderId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippingFee = 30000m,
                            Status = 1,
                            SubTotal = 500000m,
                            TotalAmount = 530000m,
                            UserAddressId = 2,
                            UserId = "user2"
                        },
                        new
                        {
                            OrderId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippingFee = 30000m,
                            Status = 1,
                            SubTotal = 1500000m,
                            TotalAmount = 1530000m,
                            UserAddressId = 3,
                            UserId = "user3"
                        },
                        new
                        {
                            OrderId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippingFee = 50000m,
                            Status = 1,
                            SubTotal = 4000000m,
                            TotalAmount = 4050000m,
                            UserAddressId = 4,
                            UserId = "user4"
                        },
                        new
                        {
                            OrderId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippingFee = 50000m,
                            Status = 1,
                            SubTotal = 2500000m,
                            TotalAmount = 2550000m,
                            UserAddressId = 5,
                            UserId = "user5"
                        });
                });

            modelBuilder.Entity("TechGearAPI.Models.OrderDetailAPI", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VariantDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("orderDetailAPIs");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            OrderId = 1,
                            ProductName = "Laptop ASUS ROG",
                            ProductVariantId = 1,
                            Quantity = 1,
                            UnitPrice = 20000000m,
                            VariantDescription = "Default"
                        },
                        new
                        {
                            OrderDetailId = 2,
                            OrderId = 2,
                            ProductName = "Mouse Logitech",
                            ProductVariantId = 2,
                            Quantity = 1,
                            UnitPrice = 500000m,
                            VariantDescription = "Default"
                        },
                        new
                        {
                            OrderDetailId = 3,
                            OrderId = 3,
                            ProductName = "Keyboard Razer",
                            ProductVariantId = 3,
                            Quantity = 1,
                            UnitPrice = 1500000m,
                            VariantDescription = "Default"
                        },
                        new
                        {
                            OrderDetailId = 4,
                            OrderId = 4,
                            ProductName = "Monitor Dell",
                            ProductVariantId = 4,
                            Quantity = 1,
                            UnitPrice = 4000000m,
                            VariantDescription = "Default"
                        },
                        new
                        {
                            OrderDetailId = 5,
                            OrderId = 5,
                            ProductName = "Sony Headphone",
                            ProductVariantId = 5,
                            Quantity = 1,
                            UnitPrice = 2500000m,
                            VariantDescription = "Default"
                        });
                });

            modelBuilder.Entity("TechGearAPI.Models.PaymentAPI", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId");

                    b.ToTable("paymentAPIs");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 20050000m,
                            Method = 1,
                            OrderId = 1,
                            PaymentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TransactionId = "TRANS001"
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 530000m,
                            Method = 1,
                            OrderId = 2,
                            PaymentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TransactionId = "TRANS002"
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 1530000m,
                            Method = 1,
                            OrderId = 3,
                            PaymentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TransactionId = "TRANS003"
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 4050000m,
                            Method = 1,
                            OrderId = 4,
                            PaymentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TransactionId = "TRANS004"
                        },
                        new
                        {
                            PaymentId = 5,
                            Amount = 2550000m,
                            Method = 1,
                            OrderId = 5,
                            PaymentDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TransactionId = "TRANS005"
                        });
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductAPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("productAPIs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            ImageUrl = "laptop1.jpg",
                            Name = "Laptop ASUS ROG"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CategoryId = 2,
                            ImageUrl = "mouse.jpg",
                            Name = "Mouse Logitech G102"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CategoryId = 3,
                            ImageUrl = "keyboard.jpg",
                            Name = "Keyboard Razer"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            CategoryId = 4,
                            ImageUrl = "monitor.jpg",
                            Name = "Monitor Dell 27\""
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            CategoryId = 5,
                            ImageUrl = "headphone.jpg",
                            Name = "Sony Headphone"
                        });
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductImageAPI", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("productImageAPIs");
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductOptionAPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("productOptionAPIs");
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductOptionValueAPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductOptionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductOptionId");

                    b.ToTable("productOptionValueAPIs");
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductVariantAPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("productVariantAPIs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 20000000m,
                            ProductId = 1,
                            ProductVariantId = 0,
                            SKU = "SKU-001",
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Price = 500000m,
                            ProductId = 2,
                            ProductVariantId = 0,
                            SKU = "SKU-002",
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Price = 1500000m,
                            ProductId = 3,
                            ProductVariantId = 0,
                            SKU = "SKU-003",
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Price = 4000000m,
                            ProductId = 4,
                            ProductVariantId = 0,
                            SKU = "SKU-004",
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            Price = 2500000m,
                            ProductId = 5,
                            ProductVariantId = 0,
                            SKU = "SKU-005",
                            Stock = 40
                        });
                });

            modelBuilder.Entity("TechGearAPI.Models.UserAddressAPI", b =>
                {
                    b.Property<int>("UserAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAddressId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("userAddressAPIs");

                    b.HasData(
                        new
                        {
                            UserAddressId = 1,
                            AddressLine = "HCM",
                            District = "Q1",
                            FullName = "User 1",
                            IsDefault = true,
                            PhoneNumber = "111",
                            Province = "HCM",
                            UserId = "user1",
                            Ward = "Ward 1"
                        },
                        new
                        {
                            UserAddressId = 2,
                            AddressLine = "HN",
                            District = "Ba Dinh",
                            FullName = "User 2",
                            IsDefault = true,
                            PhoneNumber = "222",
                            Province = "HN",
                            UserId = "user2",
                            Ward = "Ward 2"
                        },
                        new
                        {
                            UserAddressId = 3,
                            AddressLine = "DN",
                            District = "Hai Chau",
                            FullName = "User 3",
                            IsDefault = true,
                            PhoneNumber = "333",
                            Province = "DN",
                            UserId = "user3",
                            Ward = "Ward 3"
                        },
                        new
                        {
                            UserAddressId = 4,
                            AddressLine = "CT",
                            District = "Ninh Kieu",
                            FullName = "User 4",
                            IsDefault = true,
                            PhoneNumber = "444",
                            Province = "CT",
                            UserId = "user4",
                            Ward = "Ward 4"
                        },
                        new
                        {
                            UserAddressId = 5,
                            AddressLine = "HP",
                            District = "Hong Bang",
                            FullName = "User 5",
                            IsDefault = true,
                            PhoneNumber = "555",
                            Province = "HP",
                            UserId = "user5",
                            Ward = "Ward 5"
                        });
                });

            modelBuilder.Entity("TechGearAPI.Models.VariantOptionValueAPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductOptionValueId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantAPIId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductOptionValueId");

                    b.HasIndex("ProductVariantAPIId");

                    b.HasIndex("ProductVariantId", "ProductOptionValueId")
                        .IsUnique();

                    b.ToTable("variantOptionValueAPIs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TechGearAPI.Models.ApplicationUserAPI", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TechGearAPI.Models.ApplicationUserAPI", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechGearAPI.Models.ApplicationUserAPI", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TechGearAPI.Models.ApplicationUserAPI", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechGearAPI.Models.CartItemAPI", b =>
                {
                    b.HasOne("TechGearAPI.Models.ProductVariantAPI", "ProductVariant")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechGearAPI.Models.ApplicationUserAPI", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechGearAPI.Models.ComboItemAPI", b =>
                {
                    b.HasOne("TechGearAPI.Models.ComboAPI", "Combo")
                        .WithMany("ComboItems")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechGearAPI.Models.ProductVariantAPI", "ProductVariant")
                        .WithMany("ComboItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("TechGearAPI.Models.OrderAPI", b =>
                {
                    b.HasOne("TechGearAPI.Models.UserAddressAPI", "UserAddress")
                        .WithMany("Orders")
                        .HasForeignKey("UserAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechGearAPI.Models.ApplicationUserAPI", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserAddress");
                });

            modelBuilder.Entity("TechGearAPI.Models.OrderDetailAPI", b =>
                {
                    b.HasOne("TechGearAPI.Models.OrderAPI", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechGearAPI.Models.ProductVariantAPI", "ProductVariant")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("TechGearAPI.Models.PaymentAPI", b =>
                {
                    b.HasOne("TechGearAPI.Models.OrderAPI", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductAPI", b =>
                {
                    b.HasOne("TechGearAPI.Models.BrandAPI", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechGearAPI.Models.CategoryAPI", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductImageAPI", b =>
                {
                    b.HasOne("TechGearAPI.Models.ProductAPI", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechGearAPI.Models.ProductVariantAPI", "ProductVariant")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductOptionAPI", b =>
                {
                    b.HasOne("TechGearAPI.Models.ProductAPI", "Product")
                        .WithMany("ProductOptions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductOptionValueAPI", b =>
                {
                    b.HasOne("TechGearAPI.Models.ProductOptionAPI", "ProductOption")
                        .WithMany("ProductOptionValues")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductOption");
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductVariantAPI", b =>
                {
                    b.HasOne("TechGearAPI.Models.ProductAPI", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechGearAPI.Models.UserAddressAPI", b =>
                {
                    b.HasOne("TechGearAPI.Models.ApplicationUserAPI", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechGearAPI.Models.VariantOptionValueAPI", b =>
                {
                    b.HasOne("TechGearAPI.Models.ProductOptionValueAPI", "ProductOptionValue")
                        .WithMany("ProductVariantOptions")
                        .HasForeignKey("ProductOptionValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechGearAPI.Models.ProductVariantAPI", null)
                        .WithMany("ProductVariantOptions")
                        .HasForeignKey("ProductVariantAPIId");

                    b.HasOne("TechGearAPI.Models.ProductVariantAPI", "ProductVariant")
                        .WithMany("VariantOptionValues")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductOptionValue");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("TechGearAPI.Models.ApplicationUserAPI", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("TechGearAPI.Models.BrandAPI", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechGearAPI.Models.CategoryAPI", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechGearAPI.Models.ComboAPI", b =>
                {
                    b.Navigation("ComboItems");
                });

            modelBuilder.Entity("TechGearAPI.Models.OrderAPI", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductAPI", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProductOptions");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductOptionAPI", b =>
                {
                    b.Navigation("ProductOptionValues");
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductOptionValueAPI", b =>
                {
                    b.Navigation("ProductVariantOptions");
                });

            modelBuilder.Entity("TechGearAPI.Models.ProductVariantAPI", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("ComboItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariantOptions");

                    b.Navigation("VariantOptionValues");
                });

            modelBuilder.Entity("TechGearAPI.Models.UserAddressAPI", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
